using Microsoft.Data.SqlClient;
using System.Text.RegularExpressions;

public class Database : IDisposable
{
    public static string DATABASE_SQL = "database.sql";
    private SqlConnection connection;

    public SqlConnection Connection {get => connection; }

    public Database(DatabaseCredentials credentials)
    {
        var conBuilder = credentials.ConnectionBuilder;
        
        connection = new SqlConnection(conBuilder.ConnectionString);
        connection.Open();
    }

    public static void Create(DatabaseCredentials credentials)
    {
        string sql = File.ReadAllText(DATABASE_SQL);
        
        var conBuilder = credentials.ConnectionBuilderNoDB;
        using(var connection = new SqlConnection(conBuilder.ConnectionString)) {
        connection.Open();
        
        // Regex generated by AI to stop SqlInjections
        // Very important for a school project that noone will try to attack
        if(!Regex.IsMatch(credentials.DatabaseName, @"^[a-zA-Z0-9_]+$"))
        {
            throw new DatabaseException("Invalid database name");
        }

        var dbCommand = new SqlCommand($"CREATE DATABASE [{credentials.DatabaseName}]", connection);
        dbCommand.ExecuteNonQuery(); 
           
        }
        
        conBuilder = credentials.ConnectionBuilder;
        Console.WriteLine(conBuilder.ConnectionString);
        using(var connection = new SqlConnection(conBuilder.ConnectionString)) {
            connection.Open();
            
            var tableCommand= new SqlCommand(sql, connection);
            tableCommand.ExecuteNonQuery();
           
        }
    }
    
    public static bool Exists(DatabaseCredentials credentials) 
    {
        var conBuilder = credentials.ConnectionBuilderNoDB;
        
        bool exists = true;
        using (var connection = new SqlConnection(conBuilder.ConnectionString))
        {
            connection.Open();
            using var command = new SqlCommand("SELECT name FROM sys.databases WHERE name = @name", connection);
            command.Parameters.AddWithValue("@name", credentials.DatabaseName);

            var reader = command.ExecuteScalar(); 
            if(reader == null) exists = false;
        }

        return exists;
    }
    
    public void Dispose()
    {
        connection.Dispose();
    }

}
